# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Maps_code' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Maps_code
	pod 'GoogleMaps', '~> 3.7.0'

  target 'Maps_codeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Maps_codeUITests' do
    # Pods for testing
  end

end
